name: uploadcare_client
description: Flutter Uploadcare service client
version: 0.0.1
author: Konstantin Kai <kosyak46@gmail.com>
homepage: https://github.com/KonstantinKai/uploadcare_client
repository: https://github.com/KonstantinKai/uploadcare_client
issue_tracker: https://github.com/KonstantinKai/uploadcare_client/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  crypto: ^2.1.3
  meta: ^1.1.7
  mime_type: ^0.2.4
  http_parser: ^3.1.3
  equatable: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3
  dotenv: ^1.0.0
  mockito: ^4.1.1