name: uploadcare_client
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+2
  crypto: 2.1.3
  meta: 1.1.7
  mime_type: 0.2.4
  http_parser: 3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dotenv: ^1.0.0